version: '3.8'

services:
  phone:
    build:
      context: ./phone
      dockerfile: Dockerfile
    container_name: alpha-phone
    ports:
      - "8081:8081"   
      - "19000:19000" 
      - "19001:19001" 
      - "19002:19002" 
    volumes:
      - ./phone:/app
      - /app/node_modules
      - /app/.expo
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      # Укажите IP адрес вашего компьютера в локальной сети (например, 192.168.1.100)
      - EXPO_PACKAGER_PROXY_URL=http://192.168.0.108:8081
      - EXPO_NO_TELEMETRY=1
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - alpha-network
    restart: unless-stopped

  webalpha:
    build:
      context: ./webalpha
      dockerfile: Dockerfile
    container_name: alpha-web
    ports:
      - "3000:3000"
    volumes:
      - ./webalpha:/app
      - /app/node_modules
    networks:
      - alpha-network

networks:
  alpha-network:
    driver: bridge
